version: "3"
services:
  db:
    image: postgres
    container_name: marketplace_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertyuiop123456
      - POSTGRES_DB=marketplace
    ports:
      - 5555:5432
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    environment:
      - DB_KIND=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=qwertyuiop123456
      - DB_NAME=marketplace
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
