FROM python:3.9-slim-bullseye


WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# CURL installation for healthcheck*
RUN apt update && apt install curl -y && rm -rf /var/lib/apt/lists/*

# LDAP installation
RUN apt update && apt install -y python-dev libldap2-dev libsasl2-dev libssl-dev gcc build-essential libpq-dev libpq5

# PDM installation
RUN pip install --no-cache-dir pip setuptools wheel
RUN pip install --no-cache-dir pdm==2.1.0

# Copy all sources files
COPY ./src ./

# Expose Server Port
EXPOSE 8080

# Development launch command
CMD [ "pdm", "run", "serve" ]