version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: marketplace_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwertyuiop123456
      - POSTGRES_DB=marketplace
    ports:
      - 5432:5432
