version: '3.6'

networks:
  marketplace-net:
    name: marketplace-net

volumes:
  build:
    context: .
    dockerfile: Dockerfile
  healthcheck:
    test: ["CMD", "curl", "--fail", "http://localhost:80${MARKETPLACE_API_ROOT_PATH_PROD}"]
    interval: 1m
    timeout: 30s
    retries: 3
    start_period: 10s
  environment:
    - 'ENV=production'
    - 'TZ=${MARKETPLACE_API_TZ}'
    - 'LOG_LEVEL=${MARKETPLACE_API_LOG_LEVEL_PROD}'
    - 'CORS_ORIGINS=${MARKETPLACE_API_CORS_ORIGINS_PROD}'
    - 'ROOT_PATH=${MARKETPLACE_API_ROOT_PATH_PROD}'
    - 'DATABASE_URL=mongodb://${MARKETPLACE_DATABASE_USER_PROD}:${MARKETPLACE_DATABASE_PASSWORD_PROD}@${MARKETPLACE_DATABASE_NAME}:27017'
    - 'DATABASE_DB=${MARKETPLACE_DATABASE_DB_PROD}'
    - 'S3_REGION=${MARKETPLACE_S3_REGION_PROD}'
    - 'S3_ACCESS_KEY=${MARKETPLACE_S3_ACCESS_KEY_PROD}'
    - 'S3_SECRET_ACCESS_KEY=${MARKETPLACE_S3_SECRET_ACCESS_KEY_PROD}'
    - 'S3_URL=http://${MARKETPLACE_S3_NAME}:9000'
    - 'S3_BUCKET_NAME=${MARKETPLACE_S3_BUCKET_NAME_PROD}'
    - 'VERSION=${MARKETPLACE_API_VERSION_PROD}'
  networks:
    - marketplace-net 
  ports:
    - ${MARKETPLACE_API_PORT}:80
  depends_on:
    - marketplace-database
    - marketplace-s3
  restart: unless-stopped

  marketplace-database:
    container_name: '${MARKETPLACE_DATABASE_NAME}'
    image: ${MARKETPLACE_DATABASE_IMG}:${MARKETPLACE_DATABASE_VERSION_PROD}
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${MARKETPLACE_DATABASE_USER_PROD}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MARKETPLACE_DATABASE_PASSWORD_PROD}'
    volumes:
      - marketplace-database-data:/data/db:rw
    networks:
      - marketplace-net
    ports:
      - ${MARKETPLACE_DATABASE_PORT}:27017
    restart: unless-stopped

  marketplace-database-tool:
    container_name: '${MARKETPLACE_DATABASE_TOOL_NAME}'
    image: ${MARKETPLACE_DATABASE_TOOL_IMG}:${MARKETPLACE_DATABASE_TOOL_VERSION_PROD}
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=monokai'
      - 'ME_CONFIG_MONGODB_SERVER=${MARKETPLACE_DATABASE_NAME}'
      - 'ME_CONFIG_MONGODB_PORT=27017'
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=${MARKETPLACE_DATABASE_USER_PROD}'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=${MARKETPLACE_DATABASE_PASSWORD_PROD}'
      - 'ME_CONFIG_BASICAUTH_USERNAME=${MARKETPLACE_DATABASE_TOOL_USER_PROD}'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=${MARKETPLACE_DATABASE_TOOL_PASSWORD_PROD}'
    networks:
      - marketplace-net
    ports:
      - ${MARKETPLACE_DATABASE_TOOL_PORT}:8081
    depends_on:
      - marketplace-database
    restart: unless-stopped

  marketplace-s3:
    container_name: '${MARKETPLACE_S3_NAME}'
    image: ${MARKETPLACE_S3_IMG}:${MARKETPLACE_S3_VERSION_PROD}
    command: server --address "${MARKETPLACE_S3_NAME}:9000" --console-address "${MARKETPLACE_S3_NAME}:9001" /data
    environment:
      - 'MINIO_ROOT_USER=${MARKETPLACE_S3_ACCESS_KEY_PROD}'
     
